version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - DEBUG: "1"
      - DB_NAME: myproject
      - DB_USER: myprojectuser
      - DB_PASS: myprojectpass
      - DB_SERVICE: db
      - DB_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER= myprojectuser
      - POSTGRES_PASSWORD= myprojectpassword
      - POSTGRES_DB= myproject

volumes:
  postgres_data:
